# Generated by Django 4.1.5 on 2023-01-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sudoku_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sudoku_image_upload', models.ImageField(upload_to='sudoku_input/')),
            ],
        ),
    ]
